import Head from "next/head";

import Title from "@/components/Title";
import Alert from "@/components/Alert";

import pagesStyles from "@/styles/Pages.module.css";
import styles from "@/styles/StaticRendering.module.css";

export default function OnDemandIncrementalStaticRegeneration() {
    return (
        <>
            <Head>
                <title>On Demand Incremental Static Regeneration</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={pagesStyles.page}>
                <main className={pagesStyles.main}>
                    <Title borderBlack>Esta é uma página que renderiza de forma estática</Title>

                    <Alert>
                        <p>
                            <span className={styles.focus}>EM CONSTRUÇÃO...</span>
                        </p>
                    </Alert>
                </main>
            </div>
        </>
    )
}
