import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";

import DogCard from "@/components/DogCard";
import Resume from "@/components/Resume";
import Title from "@/components/Title";
import Alert from "@/components/Alert";

import img1 from '@/assets/static-rendering/static-rendering-with-fetch1.png'
import img2 from '@/assets/static-rendering/static-rendering-with-fetch2.png'
import hehe from '@/assets/static-rendering/hehe.gif'

import styles from "@/styles/StaticRendering.module.css";

interface DogData {
    name: string,
    age: number,
    breed: string,
    veterinary_history: {
        vaccines: Array<string>,
        deworming: string,
        castration: boolean
    },
    image: string
};

const fetcher = (url: string) => fetch(url).then((res) => res.json());

function DogCardSkeleton() {
    return (
        <div style={{ width: '300px', height: '300px', backgroundColor: '#d6d6d6' }} />
    )
}

export default function StaticRenderingWithFetch() {
    const { data, isLoading } = useSWR("/api/with-fetch", fetcher);

    return (
        <>
            <Head>
                <title>Renderização Estárica | Static Rendering</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.page}>
                <main className={styles.main}>
                    <Title borderBlack>
                        Esta é uma página que renderiza de forma estática e faz um fetch do lado do cliente
                    </Title>

                    {isLoading
                        ? <DogCardSkeleton />
                        : <div className={styles.dogWrapper}>
                            {data.map((dog: DogData) => (
                                <DogCard {...dog} />
                            ))}
                        </div>
                    }

                    <section className={styles.section}>
                        <p>
                            Neste exemplo queremos mostrar uma lista de Doguinhos para adoção. Logo, precisaremos de uma API que nos forneça os dados necessários para essa listagem.
                        </p>

                        <div style={{ display: 'flex', alignItems: 'center' }}>
                            <p>
                                Usaremos a Renderização Estática com um Fetch do lado do cliente. Este padrão funciona bem quando você quer atualizar dados em cada solicitação (mas os nossos serão sempres os mesmos).
                            </p>
                            <Image
                                className={styles.logo}
                                src={hehe}
                                alt="Next.js logo"
                                width={60}
                                height={60}
                                priority
                            />
                        </div>

                        <p>
                            <span className={styles.focus}>O HTML é gerado em tempo de build</span> e renderizado com o componente esqueleto, que será substituído pelo componente com os dados da listagem dinâmica após o <span className={styles.focus}>fetch dos dados no lado do cliente</span>.
                            <br />
                            Utilizamos SWR (lib) para fazer o fetch dos dados no cliente. E construímos uma rota de API personalizada para buscar e retornar os dados dos Doguinhos.
                            <br />
                            <span className={styles.focus}>Este padrão também é facilmente cacheável através de uma CDN.</span>
                        </p>

                        <Alert type="warn">
                            <p>
                                <span className={styles.focus}>INDICADO PARA</span> páginas que contém dados que mudam a cada requisição; e para páginas que contém componentes com placeholder estáveis.
                            </p>
                        </Alert>
                    </section>

                    <Image
                        className={styles.logo}
                        src={img1}
                        alt="Next.js logo"
                        width={600}
                        height={380}
                        priority
                    />

                    <p>
                        O arquivo HTML pré-gerado é enviado ao cliente quando o usuário solicita a página. O usuário inicialmente vê a UI do esqueleto sem nenhum dado. O cliente busca os dados da rota da API, recebe a resposta e mostra a listagem.
                    </p>

                    <Image
                        className={styles.logo}
                        src={img2}
                        alt="Next.js logo"
                        width={600}
                        height={380}
                        priority
                    />

                    <Resume
                        title='Renderização Estática com Fetch de dados'
                        qualifications={[
                            { name: 'Time To First Byte', score: 'good' },
                            { name: 'First Contentful Paint', score: 'good' },
                            { name: 'Largest Contentful Paint', score: 'warn' },
                            { name: 'Time To Interactive', score: 'good' },
                            { name: 'Cumulative Layout Shift', score: 'warn' },
                            { name: 'First Input Delay', score: 'good' },
                            { name: 'Fast Build Times', score: 'good' },
                            { name: 'Low Server Costs', score: 'warn' },
                            { name: 'Easy Rollbacks', score: 'good' },
                            { name: 'Reliable uptime', score: 'warn' },
                            { name: 'Dynamic Content', score: 'warn' },
                            { name: 'Scalable infraestructure', score: 'warn' },
                        ]}
                    />

                    <section>
                        <p>
                            Embora a renderização estática com fetch do lado do cliente nos dê um bom TTFB e FCP, o LCP não é o ideal, pois o "maior conteúdo" só pode ser exibido depois de obtermos os dados das listagens da rota da API.
                            <br />
                            Também há uma forte possibilidade de mudanças de layout, especialmente se o tamanho do esqueleto da UI não corresponder ao conteúdo renderizado eventualmente.
                            <br />
                            Outra desvantagem é que essa abordagem pode resultar em custos de servidor mais altos, já que chamamos a rota da API uma vez por solicitação de página.
                            <br />
                            O Next.js oferece algumas soluções, conforme discutido nas seções a seguir, para melhorar o desempenho do seu aplicativo ao trabalhar com dados dinâmicos.
                        </p>
                    </section>
                </main>
            </div>
        </>
    );
}
